config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/secretary/day.:format', :to => 'secretary#day'
get '/secretary/interval.:format', :to => 'secretary#interval'

resources :pocket_calendars do
  collection do
    put 'manage_special_day'
    put 'change_month'
  end
end

resources :day_types

resources :week_patterns

app/models/week_pattern.rb
# == Schema Information
#
# Table name: week_patterns
#
#  id   :integer          not null, primary key
#  name :string(255)
#  days :text
#

class WeekPattern < ActiveRecord::Base
  unloadable

  serialize :days

  has_many :pocket_calendars

  validates_presence_of :name, :days

  DAYS = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"].freeze

  def self.for_select
    WeekPattern.all.map{ |wp| [wp.name, wp.id] }
  end

  def day_types
    dt_ids = days.values.uniq
    dts = DayType.find(dt_ids).inject({}){ |hsh, dt| hsh.tap{ |h| h[dt.id.to_s] = dt.to_hash} }
    days.map{ |wday, dt_id| { wday => dts[dt_id.to_s] } }.reduce(:merge)
  end

  DAYS.each_with_index do |day, index|
    define_method "#{day}" do
      self.days[index.to_s] rescue nil
    end
  end

  DAYS.each_with_index do |day, index|
    define_method "#{day}=" do |dt_id|
      self.days ||= {}
      self.days[index.to_s] = dt_id
    end
  end

  # TODO : smart validation on days (existing day_types, all days filled, etc.)

end

app/controllers/week_patterns_controller.rb
class WeekPatternsController < ApplicationController
  unloadable

  def index
    @week_patterns = WeekPattern.all
  end

  def new
    @week_pattern = WeekPattern.new
  end

  def create
    @week_pattern = WeekPattern.new
    @week_pattern.attributes = params[:week_pattern]

    if @week_pattern.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to week_patterns_path
    else
      render :action => 'new'
    end
  end

  def edit
    @week_pattern = WeekPattern.find(params[:id])
  end

  def update
    @week_pattern = WeekPattern.find(params[:id])
    @week_pattern.attributes = params[:week_pattern]

    if @week_pattern.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to week_patterns_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @week_pattern = WeekPattern.find(params[:id])
    @week_pattern.destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_to week_patters_path
  end

end

app/helpers/week_patterns_helper.rb
module WeekPatternsHelper

  def human_day_types(week_pattern)
    day_names  = I18n.t('date.day_names').rotate

    dt_html = []

    week_pattern.day_types.sort.map do |wday, info|
      dt_html << "#{day_names[wday.to_i]} : #{info[:name]}"
    end

    dt_html.join("<br/>").html_safe
  end

end

app/views/week_patterns/_form.html.erb
<div class="box tabular">
  <p><%= f.text_field :name, :required => true, :label => l('redmine_special_days.week_pattern.name') %></p>
  <% WeekPattern::DAYS.rotate.each_with_index do |day, index| %>
    <p><%= f.select day, DayType.for_select,
                       :required => true,
                       :label => l('date.day_names').rotate[index] %></p>
  <% end %>
</div>

app/views/week_patterns/edit.html.erb
<h2><%= l('redmine_special_days.edit_week_pattern') %></h2>

<%= labelled_form_for @week_pattern do |f| %>
  <%= render 'form', :f => f %>
  <%= submit_tag l(:button_update) %>
<% end %>

app/views/week_patterns/index.html.erb
<%= content_for :sidebar do %>
  <h3><%= link_to l('redmine_special_days.new_week_pattern'), {:action => 'new'}, :class => 'icon icon-add' %></h3>
<% end %>

<h2><%= l('redmine_special_days.week_patterns') %></h2>

<table class="list">
  <thead>
    <tr>
      <th><%= l('redmine_special_days.week_pattern.name')%></th>
      <th><%= l('redmine_special_days.week_pattern.days')%></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @week_patterns.each do |week_pattern| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= week_pattern.name %></td>
        <td align="center"><%= human_day_types(week_pattern) %></td>
        <td class="buttons">
          <%= link_to l('button_edit'), edit_week_pattern_path(week_pattern), :class => 'icon icon-edit' %>
          <%= link_to l('button_delete'), week_pattern_path(week_pattern), :class => 'icon icon-delete',
                                        :method => :delete,
                                        :confirm => l(:text_are_you_sure) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/week_patterns/new.html.erb
<h2><%= l('redmine_special_days.new_week_pattern') %></h2>

<%= labelled_form_for @week_pattern do |f| %>
  <%= render 'form', :f => f %>
  <%= submit_tag l(:button_create) %>
<% end %>