config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/secretary/day.:format', :to => 'secretary#day'
get '/secretary/interval.:format', :to => 'secretary#interval'

resources :pocket_calendars do
  collection do
    put 'manage_special_day'
    put 'change_month'
  end
end

resources :day_types

resources :week_patterns

app/controllers/day_types_controller.rb
class DayTypesController < ApplicationController
  unloadable

  def index
    @day_types = DayType.all
  end

  def new
    @day_type = DayType.new
  end

  def create
    @day_type = DayType.new
    @day_type.attributes = params[:day_type]

    if @day_type.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to day_types_path
    else
      render :action => 'new'
    end
  end

  def edit
    @day_type = DayType.find(params[:id])
  end

  def update
    @day_type = DayType.find(params[:id])
    @day_type.attributes = params[:day_type]

    if @day_type.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to day_types_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @day_type = DayType.find(params[:id])
    @day_type.destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_to day_types_path
  end

end

app/helpers/day_types_helper.rb
module DayTypesHelper
end

app/views/day_types/_form.html.erb
<div class="box tabular">
  <p><%= f.text_field :name, :required => true, :label => l('redmine_special_days.day_type.name') %></p>
  <p><%= f.text_field :color, :required => true, :label => l('redmine_special_days.day_type.color'),
                                :class => "iColorPicker" %></p>
  <p><%= f.text_field :duration, :label => l('redmine_special_days.day_type.duration') %></p>
</div>

app/views/day_types/edit.html.erb
<h2><%= l('redmine_special_days.edit_day_type') %></h2>

<%= labelled_form_for @day_type do |f| %>
  <%= render 'form', :f => f %>
  <%= submit_tag l(:button_update) %>
<% end %>

app/views/day_types/index.html.erb
<%= content_for :sidebar do %>
  <h3><%= link_to l('redmine_special_days.new_day_type'), {:action => 'new'}, :class => 'icon icon-add' %></h3>
<% end %>

<h2><%= l('redmine_special_days.day_types') %></h2>

<table class="list">
  <thead>
    <tr>
      <th><%= l('redmine_special_days.day_type.name')%></th>
      <th><%= l('redmine_special_days.day_type.color')%></th>
      <th><%= l('redmine_special_days.day_type.duration')%></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @day_types.each do |day_type| %>
      <tr class="<%= cycle('odd', 'even') %>">
        <td><%= day_type.name %></td>
        <td><div style="background: <%= day_type.color %>">&nbsp;</div></td>
        <td align="center"> <%= day_type.duration %> <%= l('redmine_special_days.hours') %></td>
        <td class="buttons">
          <%= link_to l('button_edit'), edit_day_type_path(day_type), :class => 'icon icon-edit' %>
          <%= link_to l('button_delete'), day_type_path(day_type), :class => 'icon icon-delete',
                                        :method => :delete,
                                        :confirm => l(:text_are_you_sure) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/day_types/new.html.erb
<h2><%= l('redmine_special_days.new_day_type') %></h2>

<%= labelled_form_for @day_type do |f| %>
  <%= render 'form', :f => f %>
  <%= submit_tag l(:button_create) %>
<% end %>