config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get '/secretary/day.:format', :to => 'secretary#day'
get '/secretary/interval.:format', :to => 'secretary#interval'

resources :pocket_calendars do
  collection do
    put 'manage_special_day'
    put 'change_month'
  end
end

resources :day_types

resources :week_patterns

app/models/pocket_calendar.rb
# == Schema Information
#
# Table name: pocket_calendars
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  week_pattern_id :integer
#

class PocketCalendar < ActiveRecord::Base
  unloadable

  belongs_to :week_pattern
  has_many :special_days, :order => 'date DESC'

  validates_presence_of   :name, :week_pattern_id
  validates_uniqueness_of :name

  accepts_nested_attributes_for :special_days, :allow_destroy => true

  def day_types
    @day_types ||= week_pattern.day_types
  end

  def mundane_day(day)
    day_types[day.wday.to_s]
  end

  def day(date)
    spec = special_days.find_by_date(date)
    spec ? spec.to_hash : mundane_day(date)
  end

  def interval(from, to)
    from = from.to_date
    to  = to.to_date

    spec = special_days.find_all_by_date(from..to).inject({}) do |hsh, sd|
      hsh.tap{ |h| h[sd.date.to_s] = sd.to_hash }
    end

    (from..to).inject({}) do |hsh, date|
      hsh.tap{ |h| h[date.to_s] = spec[date.to_s] || mundane_day(date) }
    end
  end

  def special_days_grouped_by_year
    special_days.group_by{ |sd| sd.date.year.to_s }
  end

end

app/controllers/pocket_calendars_controller.rb
class PocketCalendarsController < ApplicationController
  unloadable

  def index
    @pocket_calendars = PocketCalendar.all
  end

  def new
    @pocket_calendar = PocketCalendar.new
  end

  def create
    @pocket_calendar = PocketCalendar.new
    @pocket_calendar.attributes = params[:pocket_calendar]

    if @pocket_calendar.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to pocket_calendars_path
    else
      render :action => 'new'
    end
  end

  def edit
    @pocket_calendar = PocketCalendar.find(params[:id])
  end

  def update
    @pocket_calendar = PocketCalendar.find(params[:id])
    @pocket_calendar.attributes = params[:pocket_calendar]

    if @pocket_calendar.save
      respond_to do |format|
        format.js
        format.html do
          flash[:notice] = l(:notice_successful_update)
          redirect_to pocket_calendars_path
        end
      end
    else
      render :action => 'edit'
    end
  end

  def show
    @pocket_calendar = PocketCalendar.find(params[:id])
  end

  def change_month
    @calendar = PocketCalendar.find(params['calendar_id'].to_i)
    @year     = params[:year].to_i
    @month    = params[:month].to_i
    @div_id   = params[:div_id]
    @edit     = params[:edit]

    respond_to do |format|
      format.js
    end
  end

  def manage_special_day
    @calendar = PocketCalendar.find(params['calendar_id'].to_i)
    @date = params['date']
    @special_day = @calendar.special_days.find_by_date(@date)

    @special_day ||= @calendar.special_days.build(:date => @date)

    respond_to do |format|
      format.js
    end
  end

end

app/helpers/pocket_calendars_helper.rb
require 'date'
include WeekPatternsHelper

module PocketCalendarsHelper

  def week_pattern_overview(calendar)
    human_day_types(calendar.week_pattern).html_safe
  end

  def special_days_overview(calendar)
    overview = ""
    overview      << %(<ul>)
      calendar.special_days_grouped_by_year.each do |year, days|
        overview    << %(<li>#{year}</li>)
        overview      << %(<ul>)
          days.each do |day|
            overview    << %(<li>#{I18n.l day.date} : #{day.description}</li>)
          end
        overview      << %(</ul>)
      end
    overview      << %(</ul>)

    overview.html_safe
  end

  def pretty_calendar(calendar, year, month, options={})
    options ||= {}
    defaults = { :edit => false,
                 :show_today => true,
                 :nav_links => true,
                 :div_id => 'calendar-show',
                 :show_year => true }
    options = defaults.merge options

    first_day = Date.civil(year, month, 1)
    last_day  = Date.civil(year, month, -1)

    needs_nav = options[:nav_links] && options[:div_id]

    pretty_cal = ""

    pretty_cal << %(<div id="#{options[:div_id]}">)
    pretty_cal  << %(<table class="pretty_calendar" border="0" cellspacing="0" cellpadding="0">)
    pretty_cal    << %(<thead>)
    pretty_cal      << calendar_title_row(calendar, first_day,
                                          needs_nav, options[:show_year], options[:div_id], options[:edit])
    pretty_cal      << calendar_day_names
    pretty_cal    << %(</thead>)
    pretty_cal    << calendar_body(calendar, first_day, last_day, options[:edit])
    pretty_cal    << calendar_footer(calendar, options[:div_id], options[:edit]) if needs_nav
    pretty_cal << %(</table>)
    pretty_cal << %(</div>)

    pretty_cal.html_safe
  end

  def yearly_calendar(calendar, year)
    yearly_cal = ""

    (1..12).each do |mon|
      yearly_cal << %(<div class="calendar-year-months">) if mon%2 == 1

        yearly_cal << %(<div class="calendar-year-month">)
          yearly_cal << pretty_calendar(calendar, year, mon, :nav_links => false,
                                                             :show_year => false)
        yearly_cal << %(</div>)

      if mon%2 == 0
        yearly_cal << %(</div>)
        yearly_cal << %(<div style="clear:both;"></div>)
      end
    end

    yearly_cal.html_safe
  end


  def new_special_day_form(calendar, date)
    num = calendar.special_days.count

    spec_form = ""
    spec_form << %(<tr>)
      spec_form << %(<td class="special-day-date">)
        spec_form << text_field_tag("pocket_calendar_special_days_attributes_#{num}_date", date)
      spec_form << %(</td>)

      spec_form << %(<td class="special-day-description">)
      spec_form << %(</td>)

      spec_form << %(<td class="special-day-type">)
      spec_form << %(</td>)
    spec_form << %(</tr>)

    spec_form.html_safe
  end

  private

  def calendar_body(calendar, first_day, last_day, edit=false)
    start_day = first_day.beginning_of_week # monday
    end_day   = last_day.end_of_week # sunday

    cal_body     = %(<tbody>)
      calendar.interval(start_day, end_day).to_a.each_slice(7) do |week|
        cal_body  << %(<tr>)
          week.each do |date, info|
            date = date.to_date
            options = { :edit => edit,
                        :not_in_month => (date < first_day || date > last_day),
                        :calendar => calendar }
            cal_body << calendar_day(date, info, options)
          end
        cal_body  << %(</tr>)
      end
    cal_body    << %(</tbody>)

    cal_body.html_safe
  end

  def calendar_day_names
    day_names  = I18n.t('date.day_names').rotate.zip(I18n.t('date.abbr_day_names').rotate) # monday first

    dnames    = %(<tr class="day-names">)
      day_names.each do |dname, abbr_dname|
        dnames << "<th scope='col'><abbr title='#{dname}'>#{abbr_dname}</abbr></th>"
      end
    dnames   << %(</tr>)

    dnames.html_safe
  end

  def calendar_title_row(calendar, first_day, needs_nav, show_year, div_id, edit)
    title_colspan = needs_nav ? 3 : 7
    title = if show_year
              "#{first_day.year} #{I18n.t('date.month_names')[first_day.month]}"
            else
              I18n.t('date.month_names')[first_day.month]
            end

    next_month = first_day.next_month
    prev_month = first_day.prev_month
    next_year  = first_day.next_year
    prev_year  = first_day.prev_year

    next_month_link = month_change_link('>>', calendar, next_month.year, next_month.month,
                                        div_id, edit, I18n.t('redmine_special_days.next_month'))
    prev_month_link = month_change_link('<<', calendar, prev_month.year, prev_month.month,
                                        div_id, edit, I18n.t('redmine_special_days.prev_month'))
    next_year_link  = month_change_link('>>>', calendar, next_year.year, next_year.month,
                                        div_id, edit, I18n.t('redmine_special_days.next_year'))
    prev_year_link  = month_change_link('<<<', calendar, prev_year.year, prev_year.month,
                                        div_id, edit, I18n.t('redmine_special_days.prev_year'))

    title_row  = %(<tr class="title-row">)
    title_row   << %(<th colspan="1">#{prev_year_link}</th>) if needs_nav
    title_row   << %(<th colspan="1">#{prev_month_link}</th>) if needs_nav
    title_row   << %(<th colspan="#{title_colspan}" class="month-name">#{title}</th>)
    title_row   << %(<th colspan="1">#{next_month_link}</th>) if needs_nav
    title_row   << %(<th colspan="1">#{next_year_link}</th>) if needs_nav
    title_row << %(<tr>)

    title_row.html_safe
  end

  def calendar_footer(calendar, div_id, edit)
    current_month_link  = month_change_link(I18n.t('redmine_special_days.current_month'),
                                            calendar,
                                            Date.today.year, Date.today.month,
                                            div_id, edit)

    %(<thead><tr class="cal-footer"><th colspan="7">#{current_month_link}</th></tr></thead>).html_safe
  end

  def calendar_day(date, info, options={})
    defaults = {:not_in_month => false,
                :edit => false}
    options = defaults.merge options

    title = info[:name]
    title << " # #{info[:description]}" unless info[:description].blank?
    edit_title = info[:description] ? "" : I18n.t('redmine_special_days.click_to_create')

    pretty_day  = %(<td )
      pretty_day << %(class = ")
        pretty_day << %(day)
        pretty_day << %( not-in-month) if options[:not_in_month]
        pretty_day << %( today) if date.today?
      pretty_day << %(")
      # TODO : can this be done with CSS?
      pretty_day << %( style="background-color: #{info[:color]}") unless options[:not_in_month]
      pretty_day << %( title="#{title}") unless options[:not_in_month]
    pretty_day << %(>)
      if options[:edit]
        pretty_day << special_day_management_link(date, options[:calendar], edit_title)
      else
        pretty_day << date.day.to_s
      end
    pretty_day << %(</td>)

    pretty_day.html_safe
  end

  def month_change_link(text, calendar, year, month, div_id, edit, title = nil)
    link_to(text,
            Rails.application.routes.url_helpers.change_month_pocket_calendars_path(
              :calendar_id => calendar.id,
              :year => year,
              :month => month,
              :edit => edit,
              :div_id => div_id),
            :remote => true,
            :method => :put,
            :title => title).html_safe
  end

  def special_day_management_link(date, calendar, title=nil)
    link_to(date.day.to_s,
            Rails.application.routes.url_helpers.manage_special_day_pocket_calendars_path(
              :calendar_id => calendar.id, :date => date),
            :remote => true,
            :method => :put,
            :title => title).html_safe
  end

end

app/views/pocket_calendars/_cal_overview.html.erb
<strong><%= l('redmine_special_days.pocket_calendar_week_pattern_overview') %> :</strong>
<br/>
<%= week_pattern_overview @pocket_calendar %>

<br/>
<br/>

<strong><%= l('redmine_special_days.pocket_calendar_special_days_overview') %> :</strong>
<br/>
<%= special_days_overview @pocket_calendar %>

app/views/pocket_calendars/_form.html.erb
<div class="box tabular">
  <p><%= f.text_field :name, :required => true, :label => l('redmine_special_days.pocket_calendar.name') %></p>
  <p><%= f.select :week_pattern_id, WeekPattern.for_select,
                  :required => true,
                  :label => l('redmine_special_days.pocket_calendar.week_pattern')%></p>
</div>

app/views/pocket_calendars/_manage_special_days.html.erb
<div class="splitcontentleft">
  <div class="issues box">
    <div id="special-days-form">
      <%= render 'special_days_form', :calendar => @pocket_calendar %>
    </div>
  </div>
</div>

<div class="splitcontentright">
  <div class="issues box">
    <div id="special-days-edit-cal">
      <%= render 'pretty_calendar_month', :calendar => @pocket_calendar,
                                          :year => Date.today.year,
                                          :month => Date.today.month,
                                          :options => { :div_id => 'special-days-manager',
                                                        :needs_nav => false,
                                                        :edit => true } %>
    </div>
  </div>
</div>

app/views/pocket_calendars/_overview.html.erb
<div class="splitcontentleft">
  <div class="issues box">
    <div id="cal-overview">
      <%= render 'cal_overview', :calendar => @pocket_calendar %>
    </div>
  </div>
</div>

<div class="splitcontentright">
  <div class="issues box">
    <div id="yearly-cal">
      <%= render 'pretty_calendar_year',  :calendar => @pocket_calendar,
                                          :year => Date.today.year %>
    </div>
  </div>
</div>

app/views/pocket_calendars/_pocket_calendar.html.erb
<p><%= link_to pocket_calendar.name, pocket_calendar %></p>

app/views/pocket_calendars/_pretty_calendar_month.html.erb
<%= pretty_calendar calendar, year, month, local_assigns[:options] %>

app/views/pocket_calendars/_pretty_calendar_year.html.erb
<%= yearly_calendar calendar, year %>

app/views/pocket_calendars/_special_days_form.html.erb
<%= form_for calendar, :remote => true do |calendar_form| %>
  <%= calendar_form.label l('redmine_special_days.week_pattern.one') %>
  <%= calendar_form.collection_select :week_pattern_id, WeekPattern.all, :id, :name %>

  <hr />

  <table id="special-days-table">
    <tr>
      <th> <%= l('redmine_special_days.special_day.date') %> </th>
      <th> <%= l('redmine_special_days.special_day.description') %> </th>
      <th> <%= l('redmine_special_days.special_day.day_type') %> </th>
      <th> <%= l('redmine_special_days.special_day.destroy') %></th>
    </tr>
  <%= calendar_form.fields_for :special_days do |special_days_form| %>
    <tr>
      <td class="special-day-date">
        <%= special_days_form.text_field :date %>
      </td>
      <td class="special-day-description">
        <%= special_days_form.text_field :description %>
      </td>
      <td "special-day-day-type">
        <%= special_days_form.collection_select :day_type_id, DayType.all, :id, :name %>
      </td>

      <td "special-day-destroy">
        <% unless special_days_form.object.new_record? %>
          <%= special_days_form.check_box '_destroy' %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </table>

  <%= submit_tag %>
<% end %>

app/views/pocket_calendars/change_month.js.erb
$('#<%= @div_id %>').replaceWith('<%= escape_javascript(render "pretty_calendar_month",
                                                            :calendar => @calendar,
                                                            :year => @year,
                                                            :month => @month,
                                                            :options => { :div_id => @div_id, :edit => @edit })%>')

app/views/pocket_calendars/edit.html.erb
<h2><%= l('redmine_special_days.edit_pocket_calendar') %></h2>

<%= labelled_form_for @pocket_calendar do |f| %>
  <%= render 'form', :f => f %>
  <%= submit_tag l(:button_update) %>
<% end %>

app/views/pocket_calendars/index.html.erb
<%= content_for :sidebar do %>
  <h3><%= link_to l('redmine_special_days.day_types'),     day_types_path,     :class => 'icon icon-stats' %></h1>
  <h3><%= link_to l('redmine_special_days.week_patterns'), week_patterns_path, :class => 'icon icon-stats' %></h1>
<% end %>

<div class="contextual">
  <%= link_to l('redmine_special_days.new_pocket_calendar'), {:action => 'new'}, :class => 'icon icon-add' %>
</div>

<h2><%= l('redmine_special_days.calendars') %></h2>

<div class="list_calendar">
  <%= render @pocket_calendars %>
</div>

app/views/pocket_calendars/manage_special_day.js.erb
$('#special-days-form').html("<%= j(render 'special_days_form', :calendar => @calendar) %>");

// <% unless @special_day %>
//   $('#special-days-table').append("<%= j(new_special_day_form(@calendar, @date)) %>");
// <% end %>

app/views/pocket_calendars/new.html.erb
<h2><%= l('redmine_special_days.new_pocket_calendar') %></h2>

<%= labelled_form_for @pocket_calendar do |f| %>
  <%= render 'form', :f => f %>
  <%= submit_tag l(:button_create) %>
<% end %>

app/views/pocket_calendars/update.js.erb
$('#cal-overview').html("<%= j(render 'cal_overview', :calendar => @pocket_calendar) %>");
$('#special-days-form').html("<%= j(render 'special_days_form', :calendar => @pocket_calendar) %>");
$('#yearly-cal').html("<%= j(render 'pretty_calendar_year',  :calendar => @pocket_calendar,
                                                            :year => Date.today.year) %>");
$('#special-days-edit-cal').html("<%= j(render 'pretty_calendar_month',  :calendar => @pocket_calendar,
                                                                        :year => Date.today.year,
                                                                        :month => Date.today.month,
                                                                        :options => {
                                                                          :div_id => 'special-days-manager',
                                                                          :needs_nav => false,
                                                                          :edit => true
                                                                        }) %>");